pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        APPVERSION=''
        PROJECT='roboshop'
        COMPONENT='shipping'
        REGION='us-east-1'
        ACCOUNT_ID='515138251473'
    }
    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('get code') {
            steps {
                git url: 'https://github.com/meghashyam-singh/8-4.git', branch: 'main'
            }
        }
        stage('read version') {
            steps {
                dir('shipping') {
                    script {
                        def pom = readMavenPom file: 'pom.xml'
                        APPVERSION = pom.version
                        echo "APPVERSION IS: ${APPVERSION}"
                    }
                }
            }
        }
        stage('build code') {
            steps {
                dir('shipping') {
                    sh "npm install"
                }
            }
        }
        stage('scan code') {
            environment {
                def scannerHome = tool 'sonar-8.0'
            }
            steps {
                dir('shipping') {
                    script {
                        withSonarQubeEnv('sonar-server') {
                        sh "${scannerHome}/bin/sonar-scanner"
                        }
                    }
                }
            }
        }
        stage('build image') {
            steps {
                dir('shipping') {
                    sh "docker build -t ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ."
                }
            }
        }
        stage('scan image') {
            steps {
                sh "trivy image ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} >> shipping-image-scan-report.txt"
            }
        }
        stage('push image') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds') {
                sh """
                aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
                docker tag ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                """
                }
            }
        }
    }
}
