pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        APPVERSION=''
        ACCOUNT_ID='515138251473'
        REGION='us-east-1'
        PROJECT='roboshop'
        COMPONENT='catalogue'
    }
    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('get code') {
            steps {
                git url: 'https://github.com/meghashyam-singh/8-4.git', branch: 'main'
            }
        }
        stage('read version') {
            steps {
                dir('catalogue') {
                    script {
                        def packagejson = readJSON file: 'package.json'
                        APPVERSION = packagejson.version
                        echo "APPVERSION IS: ${APPVERSION}"
                    }
                }
            }
        }
        stage('code build') {
            steps {
                dir('catalogue') {
                    sh "npm install"
                }
            }
        }
        stage('sonar-scan') {
            environment {
                def scannerHome = tool 'sonar-8.0'
            }
            steps {
                dir('catalogue') {
                    script {
                        withSonarQubeEnv('sonar-server') {
                        sh "${scannerHome}/bin/sonar-scanner"
                        }
                    }
                }
            }
        }
        stage('image build') {
            steps {
                sh "docker build -t ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ./catalogue"
            }
        }
        stage('scan image') {
            steps {
                sh "trivy image ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} >> catalogue-image-scan-report.txt"
            }
        }
        stage('image-push') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds') {
                    sh """
                    aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
                    docker tag ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    """
                }
            }
        }
    }
}