pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        APPVERSION=''
        REGION='us-east-1'
        PROJECT='roboshop'
        COMPONENT='user'
        ACCOUNT_ID='515138251473'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }
    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('get code') {
            steps {
                git url: 'https://github.com/meghashyam-singh/8-4.git', branch: 'main'
            }
        }
        stage('read version') {
            steps {
                dir('user') {
                    script {
                        def buildfileversion = readJSON file: 'package.json'
                        APPVERSION = buildfileversion.version
                        echo "APPVERSION IS: ${APPVERSION}"
                    }
                }
            }
        }
        stage('build code') {
            steps {
                dir('user') {
                     sh "npm install"
                }
            }
        }
        stage('code scan') {
            environment {
                def scannerHome = tool 'sonar-8.0'
            }
            steps {
                dir('user') {
                    script {
                        withSonarQubeEnv('sonar-server') {
                        sh "${scannerHome}/bin/sonar-scanner"
                        }
                    }
                }
            }
        }
        stage('quality gate') {
            steps {
                timeout(time:1, unit:'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('build-image') {
            steps {
                sh "docker build -t ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ./user"
            }
        }
        stage('scan image') {
            steps {
                sh "trivy image ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} >> trivy-image-scan-report.txt"
            }
        }
        stage('image-push') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds') {
                    sh """
                    aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
                    docker tag ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    """
                }
            }
        }
    }
}